### ISSUE TITLE
Include list of available match options

### ISSUE THREAD

**Issue by tobiasbueschel** [espanso/website#10]
The documentation already includes a list of all [available config options](https://espanso.org/docs/configuration/options/#options-reference) - it would also be helpful to include a list of all available **match** options.

For example, this could be helpful if one wants to quickly check which are valid match types:

```yml
    vars:
      - name: mydate
        type: date
    vars:
      - name: output
        type: choice
# ...
```

I've had a look through the website and also the Espanso repo, but couldn't something that quickly shows which YAML keys & values are valid.

@federico-terzi do you think this is something we should add to the website or would https://github.com/federico-terzi/espanso be a better fit?
