### ISSUE TITLE
`global_vars` not accepting YAML formatted links

### ISSUE THREAD

**Issue by baileythegreen** [espanso/website#47]
I am trying to create some global variables that are some informative text linked to a website, like this: [stackoverflow post showing how to format a link in YAML](https://stackoverflow.com/a/38007032). I can't seem to figure out the right way to set these up. I've tried searching the documentation for 'link', 'params', and 'global_vars', but haven't seen anything about doing links in YAML.

(code block updated to correct typo)

```yaml
global_vars:
  - name: formatted_link
    type: echo
    params:
      echo: [Displayed Text](url)
•••
matches:
  - trigger: :link
    replace: {{formatted_link}}
```

I get this output:

```[ERROR] unable to load match group "/Users/baileythegreen/Library/Application Support/espanso/match/email_signatures.yml"

Caused by:
    0: failed to parse YAML match group
    1: while parsing a block mapping, did not find expected key at line 21 column 31
    2: while parsing a block mapping, did not find expected key at line 21 column 31
```

(The column numbers are going to be based off of my actual text, but correspond to the first character inside the parentheses—the start of the url.)

Replacing `echo` with `format` does not seem to work, either, and I'm not sure what other kinds of params are valid. Putting the link inside quotation marks results in nothing being evaluated, but does stop the error.

**Comment by AucaCoyan** [comment]
Hello! I don't know if you typed it or it was a mistake, but I think you are missing `:` here:
```yaml
global_vars
# should be
global_vars:
```
Is that okay?

As for the issue itself, I think you can use [rich text](https://espanso.org/docs/matches/basics/#rich-text), does that work?

**Comment by baileythegreen** [comment]
The missing colon was a typo just in the minimum working example; my actual YAML file defines other global variables and they are working. I have fixed it in the original post.

I have just tried a few options with rich text, specifically markdown and html; the example in the documentation shows rich text being used as replacement text, so I have made some educated guesses about how that should fit with the global variable syntax with the `type`. (For obvious reasons, searching the documentation for `type` is not very useful.

**Markdown**
```yaml
global_vars:
  - name: formatted_link
    type: markdown
    params:
      markdown: [Displayed Text](url)
•••
matches:
  - trigger: :link
    replace: {{formatted_link}}
```
This gives the same error as before.

**HTML**
```yaml
global_vars:
  - name: formatted_link
    type: html
    params:
      html: <a href="url">Displayed Text</a>
•••
matches:
  - trigger: :link
    replace: {{formatted_link}}
```

This gives this error:

`[Espanso]: An error occurred during rendering, please examine the logs for more information.`

**Comment by smeech** [comment]
Try:
```yml
global_vars:
  - name: formatted_link
    type: echo
    params: 
      echo: <a href="http://www.google.com">Displayed Text</a>

matches:
  - trigger: :link
    html: "{{formatted_link}}"
```
You need [quotes](https://espanso.org/docs/matches/quotes/#no-quotes) around any value beginning with "`{`" and it appears that `global_vars:` can only create text variables.
